from typing import Protocol

from src.domain.user.entity import User


class UserUsecases(Protocol):
    async def create_user(self, user_data: User) -> None: ...

    async def get_all_users(self) -> list[User]: ...

    async def get_user_by_id(self, user_id: int) -> User | None: ...

    async def delete_user(self, user_id: int) -> None: ...

    async def update_user(self, user_id: int, user_data: User) -> User: ...
