from typing import Protocol

from src.domain.user.entity import User


class UserUsecases(Protocol):
    def create_user(self, user_data: User) -> None: ...

    def get_all_users(self) -> list[User]: ...

    def get_user_by_id(self, user_id: int) -> User | None: ...

    def delete_user(self, user_id: int) -> None: ...

    def update_user(self, user_id: int, user_data: User) -> User: ...
